### ISSUE TITLE
:bug: Issue when using the "editable[column name]" property with empty array data

### ISSUE THREAD

**Issue by gmarabout** [Avaiga/taipy-gui#525]
**Description**
We can make a single table column editable using the following property: `editable[column]=True`.
However this causes a stack when there is no data.

**How to reproduce**
Run the following code:
```
from taipy.gui import Gui

data = []
columns = {"0": {"title": "Name"}, "1": {"title": "Activated"}}


page = """
<|{data}|table|columns={columns}|editable[2]=True|>
"""

Gui(page=page).run(port=8000)
```

You get:
<img width="1060" alt="Screenshot 2022-12-06 at 16 09 30" src="https://user-images.githubusercontent.com/26060559/205949155-439c9133-5f04-4b2d-9ff3-858ab87f153b.png">

And in the console:

```
 * Server starting on http://127.0.0.1:8000
[2022-12-06 16:11:06,859][Taipy][ERROR] Exception on /taipy-jsx/TaiPy_root_page [GET]
Traceback (most recent call last):
  File "/Users/gmarabout/Library/Caches/pypoetry/virtualenvs/taipy-demo-job-monitoring-PuBFsu6N-py3.10/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/gmarabout/Library/Caches/pypoetry/virtualenvs/taipy-demo-job-monitoring-PuBFsu6N-py3.10/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/gmarabout/Library/Caches/pypoetry/virtualenvs/taipy-demo-job-monitoring-PuBFsu6N-py3.10/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/gmarabout/Library/Caches/pypoetry/virtualenvs/taipy-demo-job-monitoring-PuBFsu6N-py3.10/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/gmarabout/Library/Caches/pypoetry/virtualenvs/taipy-demo-job-monitoring-PuBFsu6N-py3.10/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/gmarabout/Library/Caches/pypoetry/virtualenvs/taipy-demo-job-monitoring-PuBFsu6N-py3.10/lib/python3.10/site-packages/taipy/gui/gui.py", line 1384, in __render_page
    context = page.render(self)
  File "/Users/gmarabout/Library/Caches/pypoetry/virtualenvs/taipy-demo-job-monitoring-PuBFsu6N-py3.10/lib/python3.10/site-packages/taipy/gui/_page.py", line 38, in render
    self._rendered_jsx = self._renderer.render(gui)
  File "/Users/gmarabout/Library/Caches/pypoetry/virtualenvs/taipy-demo-job-monitoring-PuBFsu6N-py3.10/lib/python3.10/site-packages/taipy/gui/renderers/__init__.py", line 54, in render
    return gui._markdown.convert(self._content)
  File "/Users/gmarabout/Library/Caches/pypoetry/virtualenvs/taipy-demo-job-monitoring-PuBFsu6N-py3.10/lib/python3.10/site-packages/markdown/core.py", line 268, in convert
    newRoot = treeprocessor.run(root)
  File "/Users/gmarabout/Library/Caches/pypoetry/virtualenvs/taipy-demo-job-monitoring-PuBFsu6N-py3.10/lib/python3.10/site-packages/markdown/treeprocessors.py", line 367, in run
    self.__handleInline(text), child
  File "/Users/gmarabout/Library/Caches/pypoetry/virtualenvs/taipy-demo-job-monitoring-PuBFsu6N-py3.10/lib/python3.10/site-packages/markdown/treeprocessors.py", line 127, in __handleInline
    data, matched, startIndex = self.__applyPattern(
  File "/Users/gmarabout/Library/Caches/pypoetry/virtualenvs/taipy-demo-job-monitoring-PuBFsu6N-py3.10/lib/python3.10/site-packages/markdown/treeprocessors.py", line 268, in __applyPattern
    node, start, end = pattern.handleMatch(match, data)
  File "/Users/gmarabout/Library/Caches/pypoetry/virtualenvs/taipy-demo-job-monitoring-PuBFsu6N-py3.10/lib/python3.10/site-packages/taipy/gui/renderers/_markdown/control.py", line 28, in handleMatch
    return _MarkdownFactory.create_element(self._gui, m.group(1), m.group(2)), m.start(0), m.end(0)
  File "/Users/gmarabout/Library/Caches/pypoetry/virtualenvs/taipy-demo-job-monitoring-PuBFsu6N-py3.10/lib/python3.10/site-packages/taipy/gui/renderers/_markdown/factory.py", line 29, in create_element
    builder_md = _Factory.call_builder(gui, control_type, properties)
  File "/Users/gmarabout/Library/Caches/pypoetry/virtualenvs/taipy-demo-job-monitoring-PuBFsu6N-py3.10/lib/python3.10/site-packages/taipy/gui/renderers/factory.py", line 583, in call_builder
    builded = builder(gui, name, all_properties)
  File "/Users/gmarabout/Library/Caches/pypoetry/virtualenvs/taipy-demo-job-monitoring-PuBFsu6N-py3.10/lib/python3.10/site-packages/taipy/gui/renderers/factory.py", line 434, in <lambda>
    ._get_dataframe_attributes()
  File "/Users/gmarabout/Library/Caches/pypoetry/virtualenvs/taipy-demo-job-monitoring-PuBFsu6N-py3.10/lib/python3.10/site-packages/taipy/gui/renderers/builder.py", line 475, in _get_dataframe_attributes
    if col_desc := next((x for x in columns.values() if x["dfid"] == k), None):
  File "/Users/gmarabout/Library/Caches/pypoetry/virtualenvs/taipy-demo-job-monitoring-PuBFsu6N-py3.10/lib/python3.10/site-packages/taipy/gui/renderers/builder.py", line 475, in <genexpr>
    if col_desc := next((x for x in columns.values() if x["dfid"] == k), None):
KeyError: 'dfid'
```
**Expected behavior**
The table appears empty.

**Runtime environment**
 - OS: MacOS
 - Browser: Chrome
 - Python 3.10.5

**Comment by FredLL-Avaiga** [comment]
Tx, I'll fix that
